### ISSUE TITLE
OAuth Error after login

### ISSUE THREAD

**Issue by jblorenzo** [gilbertparreno/instagram-integration#1]
Hi Gilbert,

I am not able to proceed after login, could you make a fix?

![screenshot_20170815-194648](https://user-images.githubusercontent.com/1080617/29315157-34cd0ab2-81f4-11e7-8365-b36f6e8265df.png)

**Comment by gilbertparreno** [comment]
Yes because it requires me permissions that needs to be approve by
instagram before going live.

**Comment by gilbertparreno** [comment]
Wait I'll try it again

**Comment by gilbertparreno** [comment]
I'm still waiting for permission approval from instagram

**Comment by gilbertparreno** [comment]
Please wait for Instagram approval.

Thanks!

**Comment by gilbertparreno** [comment]
![screen shot 2017-08-15 at 8 55 16 pm](https://user-images.githubusercontent.com/6652407/29316886-2eaf1f50-81fc-11e7-9e1b-0bd69713e585.jpg)

**Comment by jblorenzo** [comment]
Thanks Gilbert! Maybe you can add my user instead if this takes a while.

**Comment by gilbertparreno** [comment]
I asked Mina on your username but she didn't reply. What is your username
so I can add you as sandbox user.

**Comment by gilbertparreno** [comment]
I searched for your account on instagram haha and I get your username and add as sandbox user.

**Comment by jblorenzo** [comment]
my username is bennegeek, i still get the same error after i signed in.

**Comment by gilbertparreno** [comment]
please accept sandbox invite

**Comment by jblorenzo** [comment]
Done!
